### ISSUE TITLE
Plugin crash with Nextcloud

### ISSUE THREAD

**Issue by f-vt** [madebymode/traefik-modsecurity-plugin#6]
Hi,

Successfully got the plugin working, but as soon as I try to login within nextcloud it crashes.
It doesn't forward the query to modsecurity-crs container.
I've tried with cache disable but got the same error.

![image](https://github.com/madebymode/traefik-modsecurity-plugin/assets/16646471/da680317-85d8-4f5a-b794-cf94a9cbc3a2)

![image](https://github.com/madebymode/traefik-modsecurity-plugin/assets/16646471/44249932-65cb-4b8e-af2d-adaaf7c884cb)

traefik config:

commands:
```yaml
      # Enabling WAF module
      - '--experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/madebymode/traefik-modsecurity-plugin'
      - '--experimental.plugins.traefik-modsecurity-plugin.version=v1.4.5'
```

labels:
```yaml
      # WAF enable (This is a very simple plugin that proxies the query to the owasp/modsecurity apache container, and checks in its answer if it has detected something in the query (>400 response) or not). Set max body size to inspect to 1GB.
      - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.modSecurityUrl=http://waf:80
      - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.maxBodySize=1073741824
      - traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.cacheEnabled=true
```
nextcloud labels (waf middleware here):
```yaml
      - "traefik.http.routers.nextcloud.middlewares=other,nextcloud-redirectregex,security-and-proxy-headers,waf"
```

modescurity config (added allowed methods especially for Nextcloud):
```yaml
  # WAF ModSecurity https://plugins.traefik.io/plugins/644d9a72ebafd55c9c740848/mx-m-owasp-crs-modsecurity-plugin / https://github.com/madebymode/traefik-modsecurity-plugin
  # You need to have an always on web service as backend, like a dummy whoami one
  waf:
    image: owasp/modsecurity-crs:apache-alpine
    restart: always
    depends_on:
      - traefik
      - waf_dummy_whoami_for_modsecurity
    # 2 replicas as critical service (needs to be in swarm mode)
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    networks:
      - security_services
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - ANOMALY_OUTBOUND=5
      - BACKEND=http://waf_dummy_whoami_for_modsecurity
      - SERVER_NAME=waf
      - REMOTEIP_INT_PROXY=traefik
      #Native/JSON : Native better parsed from CrowdSec modsecurity parser
      - MODSEC_AUDIT_LOG_FORMAT=Native
      # Nextcloud uses a lot of methods
      - ALLOWED_METHODS=MKCOL GET HEAD POST PUT OPTIONS PROPFIND
  # The dummy whoami for modsecurity
  waf_dummy_whoami_for_modsecurity:
    image: containous/whoami
    security_opt:
      - no-new-privileges:true
    restart: always
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    networks:
      - security_services
```

Ask me anything you need for further debug if you wish.
